#!/usr/bin/env node
import { Command } from "commander";
import * as dotenv from "dotenv";
import chalk from "chalk";
import { StorageService } from "../services/StorageService";
import { MintService } from "../services/MintService";
import { MarketplaceService } from "../services/MarketplaceService";
import { GenerationService } from "../services/GenerationService";
import { Web3Service } from "../web3/Web3Service";
import {
  printNFT,
  printNFTTable,
  printTransactionTable,
  printUser,
  printStats,
  success,
  error,
  info,
} from "./display";

dotenv.config();

// ── Bootstrap ──────────────────────────────────────────────────────────────

const storage   = new StorageService();
const minter    = new MintService(storage);
const market    = new MarketplaceService(storage);
const generator = new GenerationService();

function getWeb3(): Web3Service {
  const rpc      = process.env.RPC_URL;
  const key      = process.env.PRIVATE_KEY;
  const contract = process.env.NFT_CONTRACT_ADDRESS;
  if (!rpc || !key || !contract) {
    throw new Error(
      "On-chain mode requires RPC_URL, PRIVATE_KEY, and NFT_CONTRACT_ADDRESS in .env"
    );
  }
  return new Web3Service(rpc, key, contract, storage);
}

function isOnChain(): boolean {
  return (process.env.BOT_MODE ?? "simulation") !== "simulation";
}

// ── CLI root ────────────────────────────────────────────────────────────────

const program = new Command();

program
  .name("nft-bot")
  .description(
    chalk.bold.cyan("NFT Seller Bot") + "\n\n" +
    chalk.bold("Business model:\n") +
    "  • NFTs are " + chalk.yellow("procedurally generated") + " by Claude (falls back to algorithmic if API fails).\n" +
    "  • Minting is a " + chalk.yellow("paid service") + " — fee rises with each new token (ascending curve).\n" +
    "  • Mint fee split  : " + chalk.green("50% dividends → holders") + " / " + chalk.blue("50% platform revenue") + ".\n" +
    "  • Sale split      : " + chalk.green("50% → seller") + " / " + chalk.cyan("50% dividends → holders") + ".\n" +
    "  • Dividends are " + chalk.bold("proportional to NFTs held") + " — hold more, earn more from every event.\n" +
    "  • Every holder is motivated to push prices up and bring in new buyers.\n\n" +
    chalk.dim("  Set BOT_MODE=simulation (default) | local | sepolia | polygon_amoy")
  )
  .version("1.0.0");

// ── mint ────────────────────────────────────────────────────────────────────

program
  .command("mint")
  .description(
    "Procedurally generate + mint a new NFT (paid service fee).\n" +
    "  Metadata is generated by Claude LLM; falls back to algorithmic on API failure.\n" +
    "  50% of fee → all current holders (proportional to their NFT count).\n" +
    "  50% of fee → platform revenue."
  )
  .option("-o, --owner <address>", "Who is minting (pays the fee, receives the NFT)", "alice")
  .option("-t, --theme <theme>", "Collection theme for generation (overrides COLLECTION_THEME env)")
  .option("-c, --collection <name>", "Collection name (overrides COLLECTION_NAME env)")
  .option("--uri <metadataUri>", "Metadata URI override (on-chain mode only)")
  .action(async (opts) => {
    try {
      const theme      = opts.theme      ?? process.env.COLLECTION_THEME;
      const collection = opts.collection ?? process.env.COLLECTION_NAME;

      // Preview what token ID and fee this will be
      const nextId = storage.getSettings().nextTokenId;
      const fee    = MintService.feeForToken(nextId);

      console.log();
      console.log(chalk.dim(`  Generating NFT #${nextId} (fee: ${fee.toFixed(2)} SIM)…`));

      // Collect existing names to avoid duplicates
      const existingNames = storage.getAllNFTs().map((n) => n.name);

      // ── LLM generation (with retry + fallback) ──────────────────────
      const generated = await generator.generate({
        tokenId: nextId,
        theme,
        collectionName: collection,
        existingNames,
      });

      const genBadge = generated.generatedBy === "llm"
        ? chalk.green("✦ LLM-generated")
        : chalk.yellow("⚠ Fallback (algorithmic)");
      console.log(`  ${genBadge}\n`);

      if (isOnChain()) {
        const web3 = getWeb3();
        if (!opts.uri) { error("--uri <metadataUri> is required for on-chain minting"); process.exit(1); }
        console.log(chalk.dim("  Sending mint transaction…"));
        const nft = await web3.mint({
          name: generated.name,
          description: generated.description,
          image: generated.image,
          attributes: generated.attributes,
          metadataUri: opts.uri,
        });
        success(`Minted on-chain! Token #${nft.tokenId}  tx: ${nft.mintTxHash}`);
        printNFT(nft);
      } else {
        const result = minter.mint({
          name: generated.name,
          description: generated.description,
          image: generated.image,
          attributes: generated.attributes,
          owner: opts.owner,
        });
        const { nft, mintFee, dividendPool, dividendPerToken, totalSupplyBefore, uniqueHolders, platformFee } = result;

        console.log(chalk.bold.cyan("  ✦ NFT Minted — Fee Breakdown"));
        console.log(`  Mint fee paid    : ${chalk.yellow(`${mintFee} SIM`)}`);
        if (totalSupplyBefore > 0) {
          console.log(
            `  Dividend pool    : ${chalk.green(`${dividendPool} SIM`)} ${chalk.dim("(50% of fee)")}`
          );
          console.log(
            `  Per-token share  : ${chalk.green(`${dividendPerToken} SIM`)} × ${totalSupplyBefore} token(s) ` +
            chalk.dim(`across ${uniqueHolders} holder(s)`)
          );
          console.log(chalk.dim(`  → Holders with more NFTs receive proportionally more`));
        } else {
          console.log(`  Holder dividend  : ${chalk.dim("none — you are the first minter!")}`);
        }
        console.log(`  Platform fee     : ${chalk.blue(`${platformFee} SIM`)} ${chalk.dim("(50% of fee)")}`);
        console.log();
        printNFT(nft);
        info(`Your NFT is unlisted. Use: nft-bot list -t ${nft.tokenId} -p <price> -s ${opts.owner}`);
      }
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── batch-mint ──────────────────────────────────────────────────────────────

program
  .command("batch-mint")
  .description(
    "Batch-generate and mint N NFTs using LLM (or fallback). " +
    "Each token is individually priced (ascending curve)."
  )
  .option("-n, --count <n>", "Number of NFTs to generate and mint", "5")
  .option("-o, --owner <address>", "Owner for all NFTs (simulation)", "alice")
  .option("-t, --theme <theme>", "Collection theme for generation")
  .option("-c, --collection <name>", "Collection name")
  .option("-f, --file <path>", "Optional: JSON file with pre-defined mint options (skips LLM)")
  .action(async (opts) => {
    const fs = await import("fs");
    try {
      let mintItems: import("../services/MintService").MintOptions[] = [];

      if (opts.file) {
        // Manual mode: load from file
        const raw   = fs.readFileSync(opts.file, "utf-8");
        const items = JSON.parse(raw) as Record<string, unknown>[];
        if (!Array.isArray(items)) { error("File must contain a JSON array"); process.exit(1); }
        mintItems = items.map((i) => ({
          ...i, owner: (i.owner as string) ?? opts.owner,
        })) as import("../services/MintService").MintOptions[];
      } else {
        // Auto mode: generate each NFT via LLM
        const count      = parseInt(opts.count);
        const theme      = opts.theme      ?? process.env.COLLECTION_THEME;
        const collection = opts.collection ?? process.env.COLLECTION_NAME;
        const nextId     = storage.getSettings().nextTokenId;
        const existing   = storage.getAllNFTs().map((n) => n.name);

        console.log(chalk.dim(`  Generating ${count} NFTs via LLM…`));

        for (let i = 0; i < count; i++) {
          const tokenId = nextId + i;
          process.stdout.write(chalk.dim(`  [${i + 1}/${count}] Generating token #${tokenId}… `));
          const gen = await generator.generate({ tokenId, theme, collectionName: collection, existingNames: existing });
          existing.push(gen.name);
          const badge = gen.generatedBy === "llm" ? chalk.green("LLM") : chalk.yellow("fallback");
          process.stdout.write(`${badge} — ${chalk.white(gen.name)}\n`);
          mintItems.push({ name: gen.name, description: gen.description, image: gen.image, attributes: gen.attributes, owner: opts.owner });
        }
        console.log();
      }

      if (isOnChain()) {
        const web3 = getWeb3();
        console.log(chalk.dim(`  Sending batch mint for ${mintItems.length} NFTs…`));
        const nfts = await web3.batchMint(mintItems as unknown as import("../web3/Web3Service").Web3MintOptions[]);
        success(`Batch minted ${nfts.length} NFTs on-chain`);
        printNFTTable(nfts, "Batch Minted NFTs");
      } else {
        const results  = minter.batchMint(mintItems);
        const totalFee = results.reduce((sum, r) => sum + parseFloat(r.mintFee), 0);
        success(`Batch minted ${results.length} NFTs. Total fees paid: ${totalFee.toFixed(4)} SIM`);
        printNFTTable(results.map((r) => r.nft), "Batch Minted NFTs");
      }
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── list ────────────────────────────────────────────────────────────────────

program
  .command("list")
  .description("List your NFT for sale at your chosen price.")
  .requiredOption("-t, --token <tokenId>", "Token ID to list", parseInt)
  .requiredOption("-p, --price <price>", "Your asking price (SIM or ETH)")
  .option("-s, --seller <address>", "Your address / username", "alice")
  .action(async (opts) => {
    try {
      if (isOnChain()) {
        const web3 = getWeb3();
        const hash = await web3.listForSale(opts.token, opts.price);
        success(`Listed token #${opts.token} at ${opts.price} ETH  (tx: ${hash})`);
      } else {
        const nft = storage.getNFTByTokenId(opts.token);
        if (!nft) { error(`Token #${opts.token} not found`); process.exit(1); }
        market.list(nft.id, opts.seller, opts.price);
        const updated = storage.getNFTById(nft.id)!;
        success(`"${nft.name}" (#${opts.token}) listed at ${opts.price} ${nft.currency}`);
        console.log(chalk.dim(
          `  When it sells: you receive ${(parseFloat(opts.price) * 0.5).toFixed(4)} SIM (50%) + your holder dividend share.\n` +
          `  Every other holder also earns a dividend — they want this to sell too.`
        ));
        printNFT(updated);
      }
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── delist ───────────────────────────────────────────────────────────────────

program
  .command("delist")
  .description("Remove your NFT from sale.")
  .requiredOption("-t, --token <tokenId>", "Token ID to delist", parseInt)
  .option("-o, --owner <address>", "Your address / username", "alice")
  .action(async (opts) => {
    try {
      if (isOnChain()) {
        const web3 = getWeb3();
        const hash = await web3.delist(opts.token);
        success(`Delisted token #${opts.token}  (tx: ${hash})`);
      } else {
        const nft = storage.getNFTByTokenId(opts.token);
        if (!nft) { error(`Token #${opts.token} not found`); process.exit(1); }
        market.delist(nft.id, opts.owner);
        success(`"${nft.name}" (#${opts.token}) removed from sale.`);
      }
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── buy ───────────────────────────────────────────────────────────────────────

program
  .command("buy")
  .description(
    "Buy a listed NFT.\n" +
    "  50% of the price goes to the seller; 50% is split among ALL current holders.\n" +
    "  Every holder profits — that's why they all market this collection."
  )
  .requiredOption("-t, --token <tokenId>", "Token ID to buy", parseInt)
  .option("-b, --buyer <address>", "Your address / username (simulation only)", "bob")
  .action(async (opts) => {
    try {
      if (isOnChain()) {
        const web3 = getWeb3();
        const listing = await web3.getListing(opts.token);
        if (!listing.active) { error(`Token #${opts.token} is not listed for sale`); process.exit(1); }
        console.log(chalk.dim(`  Buying token #${opts.token} for ${listing.priceEth} ETH…`));
        const hash = await web3.buy(opts.token);
        success(`Purchased token #${opts.token}  (tx: ${hash})`);
      } else {
        const nft = storage.getNFTByTokenId(opts.token);
        if (!nft) { error(`Token #${opts.token} not found`); process.exit(1); }
        const result = market.buy(nft.id, opts.buyer);
        const { sellerProceeds, dividendPool, dividendPerToken, eligibleSupply, uniqueHolders } = result;

        console.log();
        console.log(chalk.bold.cyan("  ✦ Purchase complete — Revenue breakdown"));
        console.log(`  Sale price          : ${chalk.yellow(`${result.salePrice} SIM`)}`);
        console.log(`  Seller receives     : ${chalk.green(`${sellerProceeds} SIM`)} ${chalk.dim("(50%)")}`);
        console.log(`  Dividend pool       : ${chalk.cyan(`${dividendPool} SIM`)} ${chalk.dim("(50% → holders)")}`);
        console.log(`  Per-token dividend  : ${chalk.cyan(`${dividendPerToken} SIM`)} × ${eligibleSupply} eligible token(s) ${chalk.dim(`across ${uniqueHolders} holder(s)`)}`);
        console.log(chalk.dim(`  → Holders with more NFTs earned proportionally more from this sale`));
        console.log();
        printNFT(storage.getNFTById(nft.id)!);
      }
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── transfer ─────────────────────────────────────────────────────────────────

program
  .command("transfer")
  .description("Transfer an NFT to another address without a sale (no dividends triggered).")
  .requiredOption("-t, --token <tokenId>", "Token ID", parseInt)
  .requiredOption("--to <address>", "Recipient address / username")
  .option("-f, --from <address>", "Sender address / username", "alice")
  .action(async (opts) => {
    try {
      const nft = storage.getNFTByTokenId(opts.token);
      if (!nft) { error(`Token #${opts.token} not found`); process.exit(1); }
      market.transfer(nft.id, opts.from, opts.to);
      success(`"${nft.name}" (#${opts.token}) transferred from ${opts.from} → ${opts.to}`);
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── marketplace ────────────────────────────────────────────────────────────────

program
  .command("marketplace")
  .description("Show all NFTs currently listed for sale.")
  .action(() => {
    const listed = market.getMarketplace();
    if (listed.length === 0) {
      info("No NFTs are listed. Mint one and list it: nft-bot list -t <id> -p <price>");
    } else {
      printNFTTable(listed, `Marketplace — ${listed.length} active listing(s)`);
    }
  });

// ── inventory ──────────────────────────────────────────────────────────────────

program
  .command("inventory")
  .description("Show NFTs owned by an address.")
  .option("-o, --owner <address>", "Address / username", "alice")
  .action((opts) => {
    const nfts = market.getInventory(opts.owner);
    const user = market.getUser(opts.owner);
    if (user) printUser(user);
    if (nfts.length === 0) {
      info(`${opts.owner} does not own any NFTs yet.`);
    } else {
      printNFTTable(nfts, `${opts.owner}'s Inventory — ${nfts.length} NFT(s)`);
    }
  });

// ── view ───────────────────────────────────────────────────────────────────────

program
  .command("view")
  .description("View full details of a single NFT.")
  .requiredOption("-t, --token <tokenId>", "Token ID", parseInt)
  .action(async (opts) => {
    try {
      let nft = storage.getNFTByTokenId(opts.token);
      if (isOnChain()) {
        const web3 = getWeb3();
        const listing = await web3.getListing(opts.token);
        if (nft && listing.active) { nft.price = listing.priceEth; nft.status = "listed"; }
      }
      if (!nft) { error(`Token #${opts.token} not found`); process.exit(1); }
      printNFT(nft);
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── all ──────────────────────────────────────────────────────────────────────

program
  .command("all")
  .description("List every NFT in the database.")
  .action(() => {
    const nfts = storage.getAllNFTs();
    if (nfts.length === 0) {
      info("No NFTs minted yet. Try: nft-bot mint -n 'My NFT' -d 'desc' -i 'https://...'");
    } else {
      printNFTTable(nfts, `All NFTs — ${nfts.length} total`);
    }
  });

// ── history ───────────────────────────────────────────────────────────────────

program
  .command("history")
  .description("Transaction log (last 20 events).")
  .action(() => {
    printTransactionTable(storage.getAllTransactions());
  });

// ── account ───────────────────────────────────────────────────────────────────

program
  .command("account")
  .description("Show balance and NFT holdings for an address.")
  .option("-a, --address <address>", "Address / username", "alice")
  .action(async (opts) => {
    try {
      if (isOnChain()) {
        const web3    = getWeb3();
        const balance = await web3.getBalance();
        const network = await web3.getNetwork();
        const total   = await web3.getTotalMinted();
        console.log();
        console.log(chalk.bold.cyan("  ┌─ On-chain Wallet ───────────────────────────────"));
        console.log(`  │  Address  : ${chalk.yellow(web3.walletAddress)}`);
        console.log(`  │  Balance  : ${chalk.green(`${balance} ETH`)}`);
        console.log(`  │  Network  : ${chalk.dim(network)}`);
        console.log(`  │  Total minted on-chain: ${total}`);
        console.log(chalk.bold.cyan("  └───────────────────────────────────────────────"));
        console.log();
      } else {
        const user = market.getUser(opts.address);
        if (!user) {
          info(`No account for "${opts.address}". Mint an NFT to create one.`);
        } else {
          printUser(user);
        }
      }
    } catch (e: unknown) {
      error((e as Error).message);
      process.exit(1);
    }
  });

// ── stats ─────────────────────────────────────────────────────────────────────

program
  .command("stats")
  .description("Platform statistics: total minted, revenue, holder count, etc.")
  .action(() => {
    const allNFTs  = storage.getAllNFTs();
    const allUsers = storage.getAllUsers();
    const allTxs   = storage.getAllTransactions();
    const settings = storage.getSettings();

    const holders      = new Set(allNFTs.map((n) => n.owner.toLowerCase())).size;
    const listed       = allNFTs.filter((n) => n.status === "listed").length;
    const sales        = allTxs.filter((t) => t.type === "sale");
    const totalVolume  = sales.reduce((s, t) => s + parseFloat(t.price ?? "0"), 0);
    const nextFee      = MintService.feeForToken(settings.nextTokenId);

    printStats({
      totalMinted:     allNFTs.length,
      listedNow:       listed,
      uniqueHolders:   holders,
      totalUsers:      allUsers.length,
      salesCount:      sales.length,
      totalVolume:     totalVolume.toFixed(4),
      platformRevenue: settings.platformRevenue ?? "0",
      nextMintFee:     nextFee.toFixed(4),
      nextTokenId:     settings.nextTokenId,
    });
  });

// ── price-curve ───────────────────────────────────────────────────────────────

program
  .command("price-curve")
  .description("Preview the mint service fee for upcoming tokens.")
  .option("-c, --count <n>", "Number of tokens to preview", "10")
  .action((opts) => {
    const settings = storage.getSettings();
    const next     = settings.nextTokenId;
    const count    = parseInt(opts.count);
    console.log();
    console.log(chalk.bold.cyan("  Mint Fee Curve — what the service costs per token"));
    console.log(chalk.dim("  Formula: fee = 1.00 + (tokenId − 1) × 0.50 SIM\n"));
    console.log(chalk.dim("  50% of each fee → existing holders   50% → platform\n"));
    for (let i = 0; i < count; i++) {
      const id   = next + i;
      const fee  = MintService.feeForToken(id);
      const div  = (fee * 0.5).toFixed(4);
      const bar  = "█".repeat(Math.min(Math.round(fee), 40));
      console.log(
        `  Token #${String(id).padStart(4)} → fee ${chalk.yellow(`${fee.toFixed(2)} SIM`)}` +
        `  holder div ${chalk.green(div)}  ${chalk.dim(bar)}`
      );
    }
    console.log();
  });

// ── reset ──────────────────────────────────────────────────────────────────────

program
  .command("reset")
  .description("Reset the simulation database (IRREVERSIBLE).")
  .option("--confirm", "Skip confirmation")
  .action((opts) => {
    if (!opts.confirm) {
      error("Pass --confirm to wipe the simulation database.");
      process.exit(1);
    }
    storage.reset();
    success("Simulation database reset.");
  });

program.parse(process.argv);
